### ISSUE TITLE
Typst integration doesn't work

### ISSUE THREAD

**Issue by Hofer-Julian** [conda-forge/quarto-feedstock#44]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The typst integration of the quarto package on conda-forge doesn't work.

This can be reproduced as follows:

- Install quarto from conda-forge
- Run `quarto typst`

On my machine this fails with:
```
ERROR: Error executing 'C:\checkouts\testing-ground\quarto-typst\.pixi\envs\default\Library\bin\tools\x86_64\t
ypst': The system cannot find the path specified. (os error 3)

Stack trace:
    at execProcess (file:///C:/checkouts/testing-ground/quarto-typst/.pixi/envs/default/Library/bin/quarto.js:
5297:15)
    at quarto (file:///C:/checkouts/testing-ground/quarto-typst/.pixi/envs/default/Library/bin/quarto.js:11495
3:31)
    at file:///C:/checkouts/testing-ground/quarto-typst/.pixi/envs/default/Library/bin/quarto.js:115017:15
    at eventLoopTick (ext:core/01_core.js:183:11)
```

### Installed packages

```shell
-
```

### Environment info

```shell
-
```

**Comment by mfisher87** [comment]
Thanks for the report, and apologies for the delay responding! Any help would be appreciated, as I might not have time to try stuff for a bit. I think it'd be better to pull in `typst` as a dependency in the conda recipe and find it in the `$PATH`. Since Quarto seems to be looking in a specific path there, I wonder if we'll need to patch anything to use the `typst` conda package.

**Comment by cderv** [comment]
Hopefully this will solve this 
- #52
